# I don't actually have Travis CI set up yet, because this is closed source.
# Putting it here anyway.

sudo: false

language: python

python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - sox

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

after_success:
    - pip uninstall -y sox

after_failure:
    - pip uninstall -y sox
